apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-landing-svc
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.LANDING_PAGE_PORT }}
    protocol: TCP
  selector:
    app: {{ .Values.appName }}-landing